services:
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro:latest
    restart: unless-stopped
    volumes:
      - /services/aria2/config:/config
      - /services/paperless-ngx/consume:/paperless
      - /services/kiwix/data:/kiwix
      - /home/stephen/Downloads:/downloads
    env_file: .env
    networks:
      - services

  ariang:
    container_name: ariang
    image: p3terx/ariang:latest
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    external: true
