services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:13
    restart: unless-stopped
    volumes:
      - /srv/services/forgejo/data:/data
    environment:
      USER_UID: 1000
      USER_GID: 1000
    networks:
      - default
      - services

networks:
  default:
  services:
    external: true
