services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /services/homarr/configs:/app/data/configs
      - /services/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./.env
    networks:
      - services

networks:
  services:
    external: true
