services:
  paperless-broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - /services/paperless-ngx/redis:/data
    networks:
      - default

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless-broker
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - /services/paperless-ngx/data:/usr/src/paperless/data
      - /services/paperless-ngx/media:/usr/src/paperless/media
      - /services/paperless-ngx/export:/usr/src/paperless/export
      - /services/paperless-ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_URL: https://paperless.home
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperless.home
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_TASK_WORKERS: 4
      PAPERLESS_THREADS_PER_WORKER: 2
      PAPERLESS_WEBSERVER_WORKERS: 2
      PAPERLESS_OCR_OUTPUT_TYPE: pdfa
      PAPERLESS_OCR_COLOR_CONVERSION_STRATEGY: RGB
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: always
      PAPERLESS_FILENAME_FORMAT: "{{ title }}"
    networks:
      - default

networks:
  default:
