---
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /srv/services/pyload-ng/config:/config
      - /srv/services//paperless-ngx/consume:/downloads
    ports:
      - 8005:8000
    restart: unless-stopped
