services:
  glances:
    image: nicolargo/glances:latest
    restart: unless-stopped
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/proc:ro
    environment:
      GLANCES_OPT: -w
    networks:
      - services

networks:
  services:
    external: true
