services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    volumes:
      - /srv/services/uptime-kuma/data:/app/data
    networks:
      - services

networks:
  services:
    external: true
